In [3]:
import numpy as np

A = np.array([[1, 2, 3], 
               [4, 5, 6]])

print(A)

[[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np

M = np.matrix([[1, 2, 3], 
               [4, 5, 6]])

print(M)

[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[6,5,4],
              [3,2,1]])
print(A + B)

[[7 7 7]
 [7 7 7]]


In [6]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[6,5,4],
              [3,2,1]])
print (A - B)

[[-5 -3 -1]
 [ 1  3  5]]


In [7]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [2]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[9,8],
              [7,6],
              [5,4]])
print(np.dot(A,B))
# print(A @ B)

[[ 38  32]
 [101  86]]


In [3]:
import numpy as np

A = np.array([[2,4],
              [6,2]])

B = np.array([[18],
              [34]])

C = np.linalg.inv(A) @ B

print(C)

[[5.]
 [2.]]
